server:
  port: 8010

spring:
  application:
    name: shopping-cart-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQl_DB:coonishudemodb}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Nish@1996}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone :  http://${EUREKA_HOST:localhost}:8761/eureka/

logging:
  level:
    com:
      learn: debug
