server:
  port: 9020

spring:
  application:
    name: user-service
  h2:
    console.enabled: true

  jpa:
    hibernate:
       ddl-auto: update


  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQl_DB:coonishudemodb}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Nish@1996}
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

jwt:
  secret: ${JWT_SECRET:mysecretkey}