server:
  port: 8765

spring:
  application:
    name: gateway


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

jwt:
  secret: ${JWT_SECRET:mysecretkey}

